apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: selenium-operator
  template:
    metadata:
      labels:
        name: selenium-operator
    spec:
      serviceAccountName: selenium-operator
      containers:
        - name: selenium-operator
          # Replace this with the built image name
          image: quay.io/wivos/selenium-example:v0.0.3
          command:
          - selenium-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "selenium-operator"
